openapi: 3.0.1
info:
  title: Product API
  description: Pactflow Product API demo
  version: 1.0.0
paths:
  /products:
    get:
      summary: List all products
      description: Returns all products
      operationId: getAllProducts
      responses:
        "200":
          description: successful operation
          content:
            "application/json":
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/ProductResponse'
              examples:
                application/json:
                  value:
                    - id: "1234"
                      type: "food"
                      price: 42
                      name: "pizza"
                      version: "1.0.0"
                      # see https://github.com/apiaryio/dredd/issues/1430 for why
        "400":
          description: Invalid ID supplied
          content: {}
    post:
      summary: Create a product
      description: Creates a new product
      operationId: createProduct
      requestBody:
        description: Create a new Product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        "200":
          description: successful operation
          content:
            "application/json":
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ProductResponse'
              examples:
                application/json:
                  value:
                    id: "1234"
                    name: "some product"
                    type: "food"
                    price: 42
  /products/{id}:
    get:
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductByID
      parameters:
      - name: id
        in: path
        description: ID of product to get
        schema:
          type: string
        required: true
        example: "10"
      responses:
        "200":
          description: successful operation
          content:
            "application/json":
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Cat'
                  - $ref: '#/components/schemas/ProductResponse'
              examples:
                application/json:
                  value:
                    id: "1234"
                    type: "food"
                    price: 42
                    name: "thing"
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Product not found
          content: {}
components:
  schemas:
    ProductRequest:
      allOf:
        - $ref: '#/components/schemas/Product'
    ProductResponse:
      allOf:
        - $ref: '#/components/schemas/Product'
        # If you remove the "id" from the Product definition, you cannot use the "allOf" logical operation
        # due to the "additionalProperties" issue describe
        # - type: object
        #   properties:
        #     id:
        #       type: string
    Product:
      type: object
      required:
        - name
        - price
      additionalProperties: false
      properties:
        # As above, comment out this property and uncomment the id from the ProductResponse schema
        # to see the additionalProperties issue in action
        id:
          type: string
        type:
          type: string
        name:
          type: string
        version:
          type: string
        price:
          type: number
    Cat:
      type: object
      required:
        - name
        - owner
      additionalProperties: false
      properties:
        name:
          type: string
        owner:
          type: string
